#	T-Kernel : tmmain (bcm283x)

# include main makefile (common description)
include ../rpi_bcm283x/Makefile

# ----------------------------------------------------------------------
#|History of "Makefile"
#|=====================
#|* 2016/04/28	新規作成
#|
