#! /bin/sh -e
#
# ----------------------------------------------------------------------
#     T-Kernel 2.0 Software Package
#
#     Copyright 2011 by Ken Sakamura.
#     This software is distributed under the latest version of T-License 2.x.
# ----------------------------------------------------------------------
#
#     Released by T-Engine Forum(http://www.t-engine.org/) at 2011/05/17.
#     Modified by TRON Forum(http://www.tron.org/) at 2015/06/01.
#
# ----------------------------------------------------------------------
#
#     Modified by T.Yokobayashi at 2016/03/16.
#
# ----------------------------------------------------------------------
#

#	@(#)platform () 2016/03/16
#
#	check cross platform
#
#	"SunOS-sparc"	: Solaris Ultra
#	"SunOS-i386"	: Solaris x86
#	"Linux-i686"	: Linux x86
#	"FreeBSD-i386"	: FreeBSDq x86
#	"Cygwin-i686"	: Cygwin x86
#	"mingw32-i686"	: MSYS2 mingw32 x86
#	"unknown"	: unknown platform
#
usage='usage: platform'

PATH=/usr/bin:/bin

os=`uname -s`

case $os in
  SunOS)	platform=$os-`uname -p` ;;
  Linux)	platform=$os-`uname -m` ;;
  FreeBSD)	platform=$os-`uname -p` ;;
  Darwin)	platform=$os-`uname -p` ;;
  CYGWIN*)	platform="Cygwin-`uname -m`" ;;
  MINGW32*)	platform="mingw32-`uname -m`" ;;
  *)		platform=unknown ;;
esac

echo $platform

exit 0

# ----------------------------------------------------------------------
#|History of "platform"
#|================================
#|* 2016/03/16	../tef_em1d/から、 [app_rzt1]用にコピーし修正
#|* 2016/03/16	MSYS2 の"mingw32"環境に対応
#|
